dictSeries = {'RGDPg':['A191RL1Q225SBEA', 0, 1],
              'SEP2018':['GDPC1MD',0,1],
              'SEP2019':['GDPC1MD',0,1],
              'SEP2020':['GDPC1MD',0,1],
              'Retail Sales (No Food)':['RSXFS',1,0],
              'Retail Sales (With Food)':['RRSFS',1,0],
              'Michigan Survey':['UMCSENT',1,0],
              'OECD':['CSCICP03USM665S',1,0],
              'Consumer Credit':['TOTALSL',1,0],
              'Headline CPI(C)':['CPIAUCSL',1,0],
              'Savings Rate':['PSAVERT',0,0],
              'Personal Outlays':['A068RC1',1,0],
              'New Orders of Durable Goods':['DGORDER',1,0],
              'ECI(I)':['ECIWAG',1,0],
              'Existing Home Sales':['EXHOSLUSM495S',1,0],
              'Housing Starts':['HOUST',1,0],
              'Industrial Production Index':['INDPRO',1,0],
              'PPI(I)':['WPU0911',1,0],
              'Wholesale Sales':['WHLSLRSMSA',1,0],
              'Wholesale Inventories':['WHLSLRIMSA',1,0],
              'Inventory to Sales Ratio':['WHLSLRIRSA',0,0],
              'Change in I:S':['WHLSLRIRSA',2,0],
              'Total Expenditures':['W068RCQ027SBEA',1,0],
              'Trade Balance G&S':['BOPGSTB',1,0],
              'Trade Balance G':['BOPGTB',1,0],
              'U.S. Trade Deficit':['A09021USA174NNBR',0,0],
              'U-3 UR':['UNRATE',0,0],
              'U-6 UR':['U6RATE',0,0],
              'LFPR':['CIVPART',0,0],
              'LFPRg':['CIVPART',2,0],
              'Jobless Claims':['IC4WSA',0,0],
              'Job Openings':['JTSJOL',0,0],
              'Hires':['JTSHIL',0,0],
              'Layoffs and Discharges':['JTSLDL',0,0],
              'Seperations':['JTSTSR',0,0],
              'Quits':['JTSQUR',0,0],
              'Headline CPI':['CPIAUCSL',1,0],
              'Core CPI':['CPILFESL',1,0],
              'Core PCE':['PCEPILFE',1,0],
              'PPI':['PPIACO',1,0],
              'ECI':['ECIWAG',1,0],
              'GDP Deflator':['GDPDEF',1,0],
              '5 year, 5 year forward':['T5YIFR',0,0],
              'Michigan':['MICH',0,0],
              'TIPS':['DFII10',0,0],
              'Effective ffr':['FEDFUNDS',0,0],
              'Fed Balance Sheet':['WALCL',0,0],
              'Change to Fed Balance Sheet':['WALCL',2,0],
              'Short-Term Treasury Yield(3-month)':['DGS3MO',0,0],
              'Long-Term Treasury Yield(10 year)':['DGS10',0,0],
              'S&P 500 Index':['SP500',1,0],
              'NAIRU':['NROU',0,0]}
